"""Crear modelos

Revision ID: 443ee0057df5
Revises: 
Create Date: 2023-01-17 21:11:16.682467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443ee0057df5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
